[rospy.client][INFO] 2012-12-31 16:00:17,733: init_node, name[/safety], pid[2753]
[xmlrpc][INFO] 2012-12-31 16:00:17,740: XML-RPC server binding to 0.0.0.0:0
[rospy.init][INFO] 2012-12-31 16:00:17,742: ROS Slave URI: [http://copter131:45242/]
[xmlrpc][INFO] 2012-12-31 16:00:17,742: Started XML-RPC server [http://copter131:45242/]
[rospy.impl.masterslave][INFO] 2012-12-31 16:00:17,743: _ready: http://copter131:45242/
[rospy.registration][INFO] 2012-12-31 16:00:17,756: Registering with master node http://localhost:11311
[xmlrpc][INFO] 2012-12-31 16:00:17,757: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2012-12-31 16:00:17,843: registered with master
[rospy.rosout][INFO] 2012-12-31 16:00:17,843: initializing /rosout core topic
[rospy.rosout][INFO] 2012-12-31 16:00:17,853: connected to core topic /rosout
[rospy.simtime][INFO] 2012-12-31 16:00:17,876: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2012-12-31 16:00:18,080: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2019-03-28 07:19:23,885: topic[/safety/payload_waypoint] adding connection to [http://copter131:52823/], count 0
[rospy.internal][INFO] 2019-03-28 07:19:24,335: topic[/safety/payload_waypoint] adding connection to [http://copter131:41852/], count 1
[rospy.internal][INFO] 2019-03-28 07:19:24,340: topic[/safety/payload_waypoint] adding connection to [http://copter131:45330/], count 2
[rospy.internal][INFO] 2019-03-28 07:19:24,341: topic[/safety/payload_waypoint] adding connection to [http://copter131:41852/], count 3
[rospy.internal][INFO] 2019-03-28 07:19:24,341: topic[/safety/payload_waypoint] removing connection to http://copter131:41852/
[rospy.internal][WARNING] 2019-03-28 07:19:24,350: Unknown error initiating TCP/IP socket to copter131:42840 (http://copter131:41852/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 618, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.internal][ERROR] 2019-03-28 07:19:24,351: unable to create subscriber transport: 'NoneType' object has no attribute 'buff_size'.  Will try again in 0.5s
[rospy.internal][INFO] 2019-03-28 07:19:24,458: topic[/safety/payload_waypoint] adding connection to [http://copter131:45678/], count 3
[rospy.internal][INFO] 2019-03-28 07:19:24,470: topic[/safety/payload_waypoint] adding connection to [http://copter131:41357/], count 4
[rospy.internal][INFO] 2019-03-28 07:19:24,583: topic[/safety/payload_waypoint] adding connection to [http://copter131:56973/], count 5
[rospy.internal][INFO] 2019-03-28 07:19:24,799: topic[/safety/payload_rate] adding connection to [http://copter131:52823/], count 0
[rospy.internal][INFO] 2019-03-28 07:19:24,809: topic[/safety/payload_waypoint] adding connection to [http://copter131:39574/], count 6
[rospy.internal][INFO] 2019-03-28 07:19:24,885: topic[/safety/payload_waypoint] adding connection to [http://copter131:40328/], count 7
[rospy.internal][INFO] 2019-03-28 07:19:25,103: topic[/safety/payload_waypoint] adding connection to [http://copter131:45619/], count 8
[rospy.internal][INFO] 2019-03-28 07:19:25,106: topic[/safety/payload_waypoint] adding connection to [http://copter131:41106/], count 9
[rospy.internal][INFO] 2019-03-28 07:19:25,109: topic[/safety/payload_waypoint] adding connection to [http://copter131:44616/], count 10
[rospy.internal][ERROR] 2019-03-28 07:19:25,356: Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 694, in receive_once
    if b.tell() >= 4:
AttributeError: 'NoneType' object has no attribute 'tell'

[rospy.internal][WARNING] 2019-03-28 07:19:25,357: Unknown error initiating TCP/IP socket to copter131:42840 (http://copter131:41852/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 618, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.internal][INFO] 2019-03-28 07:19:25,357: topic[/safety/payload_waypoint] removing connection to http://copter131:41852/
[rospy.internal][INFO] 2019-03-28 07:19:25,428: topic[/safety/payload_waypoint] adding connection to [http://copter131:52089/], count 11
[rospy.internal][INFO] 2019-03-28 07:19:25,505: topic[/safety/payload_waypoint] adding connection to [http://copter131:41624/], count 12
[rospy.internal][INFO] 2019-03-28 07:19:25,911: topic[/autopilot/heartbeat_onboard] adding connection to [/autopilot], count 0
[rospy.internal][INFO] 2019-03-28 07:19:25,971: topic[/autopilot/payload_waypoint] adding connection to [/autopilot], count 0
[rospy.internal][INFO] 2019-03-28 07:19:26,227: topic[/autopilot/acs_pose] adding connection to [http://copter131:47807/], count 0
[rosout][WARNING] 2019-03-28 07:19:26,394: establishing proxies for ROS /autopliot/ services
[rospy.internal][INFO] 2019-03-28 07:19:26,731: topic[/swarm_tracker/swarm_uav_states] adding connection to [http://copter131:51053/], count 0
