[rospy.client][INFO] 2019-02-27 12:15:51,577: init_node, name[/constrained_shooter], pid[3022]
[xmlrpc][INFO] 2019-02-27 12:15:51,579: XML-RPC server binding to 0.0.0.0:0
[rospy.init][INFO] 2019-02-27 12:15:51,582: ROS Slave URI: [http://copter131:42396/]
[xmlrpc][INFO] 2019-02-27 12:15:51,581: Started XML-RPC server [http://copter131:42396/]
[rospy.impl.masterslave][INFO] 2019-02-27 12:15:51,582: _ready: http://copter131:42396/
[xmlrpc][INFO] 2019-02-27 12:15:51,583: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2019-02-27 12:15:51,584: Registering with master node http://localhost:11311
[rospy.init][INFO] 2019-02-27 12:15:51,682: registered with master
[rospy.rosout][INFO] 2019-02-27 12:15:51,683: initializing /rosout core topic
[rospy.rosout][INFO] 2019-02-27 12:15:51,783: connected to core topic /rosout
[rospy.simtime][INFO] 2019-02-27 12:15:51,896: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2019-02-27 12:15:52,023: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2019-02-27 12:15:52,546: topic[/safety/payload_waypoint] adding connection to [/safety], count 0
[rospy.internal][INFO] 2019-02-27 12:15:52,754: topic[/network/send_swarm_behavior_data] adding connection to [/network], count 0
[rosout][WARNING] 2019-02-27 12:15:52,755: Inbound TCP/IP connection failed: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.
[rospy.internal][ERROR] 2019-02-27 12:15:52,760: Inbound TCP/IP connection failed:
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 321, in _tcp_server_callback
    header = read_ros_handshake_header(sock, StringIO(), buff_size)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 362, in read_ros_handshake_header
    raise ROSHandshakeException("connection from sender terminated before handshake header received. %s bytes were received. Please check sender for additional details."%b.tell())
ROSHandshakeException: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.

[rospy.internal][INFO] 2019-02-27 12:15:53,433: topic[/autopilot/acs_pose] adding connection to [http://copter131:51261/], count 0
[rospy.internal][INFO] 2019-02-27 12:15:53,435: topic[/hit_tracker/hit_uavs] adding connection to [http://copter131:59045/], count 0
[rospy.internal][INFO] 2019-02-27 12:15:53,468: topic[/air_to_air/firing_reports] adding connection to [/network], count 0
[rospy.internal][INFO] 2019-02-27 12:15:53,731: topic[/swarm_control/behavior_status] adding connection to [/swarm_control], count 0
[rosout][WARNING] 2019-02-27 12:15:53,764: Inbound TCP/IP connection failed: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.
[rospy.internal][ERROR] 2019-02-27 12:15:53,765: Inbound TCP/IP connection failed:
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 321, in _tcp_server_callback
    header = read_ros_handshake_header(sock, StringIO(), buff_size)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 362, in read_ros_handshake_header
    raise ROSHandshakeException("connection from sender terminated before handshake header received. %s bytes were received. Please check sender for additional details."%b.tell())
ROSHandshakeException: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.

[rospy.internal][INFO] 2019-02-27 12:15:53,940: topic[/swarm_control/subswarm_id] adding connection to [http://copter131:37532/], count 0
[rospy.internal][INFO] 2019-02-27 12:15:54,030: topic[/swarm_control/ap_intent] adding connection to [http://copter131:37532/], count 0
[rospy.internal][INFO] 2019-02-27 12:15:54,122: topic[/autopilot/status] adding connection to [http://copter131:51261/], count 0
[rosout][WARNING] 2019-02-27 12:15:55,770: Inbound TCP/IP connection failed: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.
[rospy.internal][ERROR] 2019-02-27 12:15:55,770: Inbound TCP/IP connection failed:
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 321, in _tcp_server_callback
    header = read_ros_handshake_header(sock, StringIO(), buff_size)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 362, in read_ros_handshake_header
    raise ROSHandshakeException("connection from sender terminated before handshake header received. %s bytes were received. Please check sender for additional details."%b.tell())
ROSHandshakeException: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.

[rosout][WARNING] 2019-02-27 12:15:59,777: Inbound TCP/IP connection failed: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.
[rospy.internal][ERROR] 2019-02-27 12:15:59,778: Inbound TCP/IP connection failed:
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 321, in _tcp_server_callback
    header = read_ros_handshake_header(sock, StringIO(), buff_size)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 362, in read_ros_handshake_header
    raise ROSHandshakeException("connection from sender terminated before handshake header received. %s bytes were received. Please check sender for additional details."%b.tell())
ROSHandshakeException: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.

[rosout][WARNING] 2019-02-27 12:16:07,788: Inbound TCP/IP connection failed: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.
[rospy.internal][ERROR] 2019-02-27 12:16:07,790: Inbound TCP/IP connection failed:
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 321, in _tcp_server_callback
    header = read_ros_handshake_header(sock, StringIO(), buff_size)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 362, in read_ros_handshake_header
    raise ROSHandshakeException("connection from sender terminated before handshake header received. %s bytes were received. Please check sender for additional details."%b.tell())
ROSHandshakeException: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.

[rosout][WARNING] 2019-02-27 12:16:23,814: Inbound TCP/IP connection failed: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.
[rospy.internal][ERROR] 2019-02-27 12:16:23,818: Inbound TCP/IP connection failed:
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 321, in _tcp_server_callback
    header = read_ros_handshake_header(sock, StringIO(), buff_size)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 362, in read_ros_handshake_header
    raise ROSHandshakeException("connection from sender terminated before handshake header received. %s bytes were received. Please check sender for additional details."%b.tell())
ROSHandshakeException: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.

[rosout][WARNING] 2019-02-27 12:16:55,854: Inbound TCP/IP connection failed: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.
[rospy.internal][ERROR] 2019-02-27 12:16:55,856: Inbound TCP/IP connection failed:
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 321, in _tcp_server_callback
    header = read_ros_handshake_header(sock, StringIO(), buff_size)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 362, in read_ros_handshake_header
    raise ROSHandshakeException("connection from sender terminated before handshake header received. %s bytes were received. Please check sender for additional details."%b.tell())
ROSHandshakeException: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.

[rosout][INFO] 2019-02-27 12:17:51,552: constrained_shooter activate request False returned False
[rosout][WARNING] 2019-02-27 12:17:59,928: Inbound TCP/IP connection failed: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.
[rospy.internal][ERROR] 2019-02-27 12:17:59,930: Inbound TCP/IP connection failed:
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 321, in _tcp_server_callback
    header = read_ros_handshake_header(sock, StringIO(), buff_size)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 362, in read_ros_handshake_header
    raise ROSHandshakeException("connection from sender terminated before handshake header received. %s bytes were received. Please check sender for additional details."%b.tell())
ROSHandshakeException: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.

[rosout][INFO] 2019-02-27 12:18:28,259: constrained_shooter activate request False returned False
[rosout][INFO] 2019-02-27 12:18:56,959: constrained_shooter activate request False returned False
[rosout][INFO] 2019-02-27 12:19:13,350: constrained_shooter activate request False returned False
[rosout][INFO] 2019-02-27 12:19:30,862: constrained_shooter activate request False returned False
[rosout][WARNING] 2019-02-27 12:20:08,041: Inbound TCP/IP connection failed: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.
[rospy.internal][ERROR] 2019-02-27 12:20:08,042: Inbound TCP/IP connection failed:
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 321, in _tcp_server_callback
    header = read_ros_handshake_header(sock, StringIO(), buff_size)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 362, in read_ros_handshake_header
    raise ROSHandshakeException("connection from sender terminated before handshake header received. %s bytes were received. Please check sender for additional details."%b.tell())
ROSHandshakeException: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.

[rosout][WARNING] 2019-02-27 12:24:24,154: Inbound TCP/IP connection failed: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.
[rospy.internal][ERROR] 2019-02-27 12:24:24,156: Inbound TCP/IP connection failed:
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 321, in _tcp_server_callback
    header = read_ros_handshake_header(sock, StringIO(), buff_size)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 362, in read_ros_handshake_header
    raise ROSHandshakeException("connection from sender terminated before handshake header received. %s bytes were received. Please check sender for additional details."%b.tell())
ROSHandshakeException: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.

[rosout][INFO] 2019-02-27 12:26:08,502: constrained_shooter activate request False returned False
[rosout][INFO] 2019-02-27 12:32:52,275: constrained_shooter activate request False returned False
[rosout][WARNING] 2019-02-27 12:32:56,262: Inbound TCP/IP connection failed: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.
[rospy.internal][ERROR] 2019-02-27 12:32:56,264: Inbound TCP/IP connection failed:
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 321, in _tcp_server_callback
    header = read_ros_handshake_header(sock, StringIO(), buff_size)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 362, in read_ros_handshake_header
    raise ROSHandshakeException("connection from sender terminated before handshake header received. %s bytes were received. Please check sender for additional details."%b.tell())
ROSHandshakeException: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.

[rosout][INFO] 2019-02-27 12:33:51,624: constrained_shooter activate request False returned False
[rosout][INFO] 2019-02-27 12:34:06,708: constrained_shooter activate request False returned False
[rosout][INFO] 2019-02-27 12:38:18,638: constrained_shooter activate request False returned False
